[pytest]
markers =
    order: test execution order
    notifier: tests related to notification functionality
    reporting: tests related to reporting module
    alr: tests related to Audit Log Reports Module
    enrollments: tests related to enrollments module
    enrollment_search: tests related to enrollment search by Renuka
    es: tests related to enrollment search by Manogna
    sit: system integration test module

    portal_login: tests related to portal login module
    es:tests related to enrollment search
    DF:tests related to detect faces
    accounts:tests related to accounts
    Image_quality:tests related to image quality
    Logo_changes:tests related to logo changes
    notes:tests related to notes
    tags:tests related to tags

    ie: tests related to Identify & Enroll module
    ie_blk: tests related to bulk enrollments
